// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svvncewelxrxpgvckvjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dm5jZXdlbHhyeHBndmNrdmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzU4MTUsImV4cCI6MjA1NjkxMTgxNX0.Fcze23X0ZPCQw4WE45lI0ccBoL9Pk_HN8VCJz53zbzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);